from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^teacher/(?P<teacher>[a-zA-Z0-9]+)/(?P<day>[a-z]+)/$', views.my_custom_sql, name='my_custom_sql'),
    url(r'^echo_admin/(?P<username>[a-zA-Z0-9]+)/(?P<password>[a-zA-Z0-9]+)/$', views.echo_admin, name='echo_admin'),
    url(r'^add_student/$', views.add_student, name='add_student'),
    url(r'^add_teacher/$', views.add_teacher, name='add_teacher'),
    url(r'^slot_delete/(?P<slot_pre_id>[0-9]+)/$', views.slot_delete, name='slot_delete'),
    url(r'^slot_edit_post/$', views.slot_edit_post, name='slot_edit_post'),
    url(r'^login/(?P<username>[a-zA-Z0-9]+)/(?P<password>[a-zA-Z0-9]+)/$', views.login, name='login'),
    url(r'^login_attendance_taker/(?P<username>[a-zA-Z0-9]+)/(?P<password>[a-zA-Z0-9]+)/$', views.login_attendance_taker, name='login_attendance_taker'),
    url(r'^login_post/$', views.login_post, name='login_post'),
    url(r'^fetch_slot_students/$', views.fetch_slot_students, name='fetch_slot_students'),
    url(r'^send_students/$', views.send_students, name='send_students'),
    url(r'^add_attendance/$', views.add_attendance, name='add_attendance') ,
    url(r'^login_sync/$', views.login_sync, name='login_sync'),
    url(r'^customAttendanceJSONData/$', views.customAttendanceJSONData, name='customAttendanceJSONData'),
    url(r'^get_student_from_slot_id/$', views.get_student_from_slot_id , name='get_student_from_slot_id'),
    url(r'^activate_code/$', views.activate_code , name='activate_code') ,
    url(r'^recieve_student_code/$', views.recieve_student_code , name='recieve_student_code') ,
    url(r'^quiz_teacher_login/$', views.quiz_teacher_login, name='quiz_teacher_login'),
    url(r'^subscribe_course/$', views.subscribe_course , name='subscribe_course'),
    url(r'^add_question_to_bank/$', views.add_question_to_bank, name='add_question_to_bank'),
    url(r'^create_quiz/$', views.create_quiz, name='create_quiz'),
    url(r'^all_subject_quiz/$', views.all_subject_quiz, name='all_subject_quiz'),
    url(r'^quiz_student_login/$', views.quiz_student_login, name='quiz_student_login'),
    url(r'^student_subscribe_course/$', views.student_subscribe_course, name='student_subscribe_course'),
    url(r'^show_subject_quizes_today/$', views.show_subject_quizes_today, name='show_subject_quizes_today'),
    url(r'^get_quiz_questions/$', views.get_quiz_questions, name='get_quiz_questions'),
    url(r'^delete_quiz/$', views.delete_quiz, name='delete_quiz'),
    url(r'^delete_question/$', views.delete_question, name='delete_question'),
    url(r'^submit_quiz_answers/$', views.submit_quiz_answers, name='submit_quiz_answers'),
    url(r'^hello_world/$', views.hello_world, name='hello_world'),
    url(r'^fetch_all_quiz_results/$', views.fetch_all_quiz_results, name='fetch_all_quiz_results'),
    url(r'^fetch_student_quiz_results/$', views.fetch_student_quiz_results, name='fetch_student_quiz_results'),
    url(r'^fetch_student_quiz_answers/$', views.fetch_student_quiz_answers, name='fetch_student_quiz_answers'),
    url(r'^get_unmarked_slots/$', views.get_unmarked_slots, name='get_unmarked_slots'),
    url(r'^teacher_scheduler/$', views.teacher_scheduler, name='teacher_scheduler'),
    url(r'^teacher_push_slots_next_3_days/$', views.teacher_push_slots_next_3_days, name='teacher_push_slots_next_3_days'),
    url(r'^get_subject_identifiers/$', views.get_subject_identifiers, name='get_subject_identifiers'),
    url(r'^delete_teacher_scheduler_slot/$', views.delete_teacher_scheduler_slot, name='delete_teacher_scheduler_slot'),
    url(r'^mark_student_present/$', views.mark_student_present, name='mark_student_present'),
    url(r'^get_teacher_schedule/$', views.get_teacher_schedule, name='get_teacher_schedule'),
    url(r'^get_student_attendance/$', views.get_student_attendance, name='get_student_attendance'),
    url(r'^get_subject_attendance/$', views.get_subject_attendance, name='get_subject_attendance'),
    url(r'^upload_student_answer_image/$', views.upload_student_answer_image, name='upload_student_answer_image'),
    url(r'^mark_unchecked_questions/$', views.mark_unchecked_questions, name='mark_unchecked_questions'),
    url(r'^fetch_unchecked_questions/$', views.fetch_unchecked_questions, name='fetch_unchecked_questions'),
    url(r'^get_student_schedule/$', views.get_student_schedule, name='get_student_schedule')   
]
